const MONGO_CONNECTION_URI_DEV_REMOTE = "SECRET"
const MONGO_CONNECTION_URI_PROD_REMOTE = "SECRET"
const MONGO_CONNECTION_URI_PROD_LOCAL = "SECRET"

export function getConnectionUrl(): string {
	if (Deno.env.get("USERNAME") == "tony") return MONGO_CONNECTION_URI_PROD_REMOTE;
	return MONGO_CONNECTION_URI_PROD_LOCAL;

	// return MONGO_CONNECTION_URI_DEV_REMOTE
}